import { useEffect } from 'react';
import { POSProvider, usePOS } from './context/POSContext';
import { LoginScreen } from './components/LoginScreen';
import { MainApp } from './components/MainApp';
import faviconUrl from '../imports/image-1.png';

// Register the PWA service worker in production builds only. The
// `virtual:pwa-register` module is generated by vite-plugin-pwa at build time
// and is not available in the Make dev preview, so we only attempt to load it
// when running on a real production deploy.
async function registerServiceWorker() {
  if (!import.meta.env.PROD) return;
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return;
  try {
    // Build the module specifier dynamically so Vite's dev-time import
    // analyzer doesn't try to resolve it.
    const spec = ['virtual', 'pwa-register'].join(':');
    const mod: any = await import(/* @vite-ignore */ spec);
    mod.registerSW?.({ immediate: true });
  } catch (err) {
    console.log(`Service worker registration skipped: ${err}`);
  }
}

function ensureMeta(name: string, content: string, attr: 'name' | 'property' = 'name') {
  let el = document.querySelector(`meta[${attr}="${name}"]`) as HTMLMetaElement | null;
  if (!el) {
    el = document.createElement('meta');
    el.setAttribute(attr, name);
    document.head.appendChild(el);
  }
  el.content = content;
}

function ensureLink(rel: string, href: string, extra?: Record<string, string>) {
  let el = document.querySelector(`link[rel="${rel}"]`) as HTMLLinkElement | null;
  if (!el) {
    el = document.createElement('link');
    el.rel = rel;
    document.head.appendChild(el);
  }
  el.href = href;
  if (extra) Object.entries(extra).forEach(([k, v]) => el!.setAttribute(k, v));
}

function AppInner() {
  const { currentUser } = usePOS();
  return currentUser ? <MainApp /> : <LoginScreen />;
}

export default function App() {
  useEffect(() => {
    const link: HTMLLinkElement =
      document.querySelector("link[rel~='icon']") ||
      (() => {
        const el = document.createElement('link');
        el.rel = 'icon';
        document.head.appendChild(el);
        return el;
      })();
    link.href = faviconUrl;
    link.type = 'image/png';

    // PWA / iOS install meta tags.
    ensureMeta('theme-color', '#3d1a6e');
    ensureMeta('apple-mobile-web-app-capable', 'yes');
    ensureMeta('apple-mobile-web-app-status-bar-style', 'black-translucent');
    ensureMeta('apple-mobile-web-app-title', '1470 POS');
    ensureMeta('mobile-web-app-capable', 'yes');
    ensureLink('apple-touch-icon', faviconUrl);

    registerServiceWorker();
  }, []);

  return (
    <POSProvider>
      <AppInner />
    </POSProvider>
  );
}